name: Auto-sync ohmyzsh git plugin

on:
  schedule:
    - cron: '0 7 * * 1'  # every Monday at 07:00 UTC
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create or switch to sync-update branch
        run: |
          git fetch origin sync-update || true
          if git show-ref --quiet refs/remotes/origin/sync-update; then
            git checkout -B sync-update origin/sync-update
          else
            git checkout -b sync-update
          fi

      - name: Download ohmyzsh git plugin files
        run: |
          mkdir -p plugins/git
          curl -sSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.plugin.zsh -o plugins/git/git.plugin.zsh
          curl -sSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.completion.zsh -o plugins/git/git.completion.zsh
          curl -sSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/plugins/git/git.plugin.bash -o plugins/git/git.plugin.bash

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Commit and push changes to sync-update
        if: steps.check_changes.outputs.changes == 'true'
        run: |
          git add plugins/git
          git commit -m "chore: sync ohmyzsh git plugin"
          git push origin sync-update

      - name: Create or update Pull Request
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message:
            chore: sync ohmyzsh git plugin
          title: Update ohmyzsh git plugin
          body: |
            This PR auto-syncs the `git` plugin from ohmyzsh.
            Source: https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git
          branch: sync-update
          delete-branch: false
