name: Auto-update completion and plugin files

on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday at 06:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # For updating files and pushing to branches
      pull-requests: write  # For creating pull requests

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download completion and plugin files
        run: |
          # Download _eza completion
          mkdir -p plugins/eza/completions
          curl -sSL https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza -o plugins/eza/completions/_eza
          
          # Clone ohmyzsh and copy plugins/git directory
          git clone --depth 1 https://github.com/ohmyzsh/ohmyzsh.git ohmyzsh
          mkdir -p plugins/git
          cp -r ohmyzsh/plugins/git/* plugins/git/
          
          # Clean up ohmyzsh folder
          rm -rf ohmyzsh

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected in one or more files."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Create pull request if changed
        if: steps.check_changes.outputs.changes == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Auto-update completion and plugin files (_eza, git plugin)
          branch: update-completions-${{ github.run_id }}
          title: Auto-update completion and plugin files
          body: |
            This PR updates the following:
            - `plugins/eza/completions/_eza` from eza-community/eza
            - `plugins/git/*` from ohmyzsh/ohmyzsh (all files in plugins/git directory)
            Workflow run: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          labels: automated-update
          delete-branch: true  # Delete temporary branch after PR merge