name: Auto-update _eza completion

on:
  schedule:
    - cron: '0 6 * * 1'  # every Monday at 06:00 UTC
  workflow_dispatch:      # allows manual trigger

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Ensure write permissions for updating files

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Download latest _eza
        run: |
          mkdir -p .zfunctions
          curl -sSL https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza -o .zfunctions/_eza
      - name: Check for changes
        id: check_changes
        run: |
          if git diff --quiet; then
            echo "No changes detected."
            echo "changes=false" >> $GITHUB_OUTPUT
          else
            echo "Changes detected."
            echo "changes=true" >> $GITHUB_OUTPUT
          fi

      - name: Update file if changed
        if: steps.check_changes.outputs.changes == 'true'
        uses: test-room-7/action-update-file@v1
        with:
          file-path: |
            .zfunctions/_eza
          commit-msg: Auto-update completion files (_eza)
          github-token: ${{ secrets.GITHUB_TOKEN }}
